# site settings
title: Stare Pobitno
subtitle: Myśl globalnie, działaj lokalnie
email: starepobitno@fastmail.fm
description: Mieszkać dobrze, żyć szczęśliwie
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Stare Pobitno
street_address:
city: Rzeszów
state: Polska
zip_code: 35-301
country: Polska
phone: patrz kontakt

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/starepobitno
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook: https://www.facebook.com/stare.pobitno/
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
